### ISSUE TITLE
request missing in generated html file

### ISSUE THREAD

**Issue by ntimo** [bukalapak/snowboard#100]
Hello,
I am the maintainer of the mailcow API docs which can be found here: https://github.com/mailcow/mailcow-apiblueprint. 

I noticed that since version 3.5.5 the requests are missing in generated html files. Please see below. When I add a word after the `+ Request` it works. But as far as I know the broken example should be fully working and is compliant with the API blueprint syntax.

Broken:
```
+ Request (application/json)
```
Working:
```
+ Request test (application/json)
```

**Comment by h4ckm03d** [comment]
@ntimo I cannot reproduce this issue using this simple apib file and snowboard version: 3.5.7

```
# My API

## GET /message
+ Request (application/json)
    + Headers

            Authorization: Basic ABC123

    + Attributes
        + platform: onsite_app (string, default)
        + type: updates (string, required)

+ Response 200 (application/json)
    + Attributes
        + data
            + type: updates (string, required)
        + meta (object, fixed)
            + http_status: 200 (number)
```

Output:
![Screen Shot 2020-01-08 at 11 06 08 AM](https://user-images.githubusercontent.com/179829/71949668-fe8bf880-3206-11ea-8eb9-f2e9bccae95d.png)

**Comment by mikesun** [comment]
> @ntimo I cannot reproduce this issue using this simple apib file and snowboard version: 3.5.7
> 
> ```
> # My API
> 
> ## GET /message
> + Request (application/json)
>     + Headers
> 
>             Authorization: Basic ABC123
> 
>     + Attributes
>         + platform: onsite_app (string, default)
>         + type: updates (string, required)
> 
> + Response 200 (application/json)
>     + Attributes
>         + data
>             + type: updates (string, required)
>         + meta (object, fixed)
>             + http_status: 200 (number)
> ```
> 
> Output:
> ![Screen Shot 2020-01-08 at 11 06 08 AM](https://user-images.githubusercontent.com/179829/71949668-fe8bf880-3206-11ea-8eb9-f2e9bccae95d.png)

If you look at your output, it's missing the request attributes: `platform`, `type`. There is only the request header and response.

**Comment by h4ckm03d** [comment]
@mikesun Noted. Thanks.
