### ISSUE TITLE
Example attribute value containing dash gets truncated at the dash

### ISSUE THREAD

**Issue by mpretty-cyro** [bukalapak/snowboard#103]
Hey @subosito, I seem to have found an issue with example values which contain dashes. When I define an action as follows:

```
## Random Post Action [POST]

+ Request - (application/json)
    + Attributes
        + value: first-second (string, required)

+ Response 200
```

The HTML generated seems to truncate the example value at the dash, so the result ends up looking like the following:

```
{
  "value": "first"
}
```

**Comment by wolfram-agentis** [comment]
Escape those values.

```
+ value: `blah-blah-blah`
```

**Comment by subosito** [comment]
Closing this, as mentioned by @wolfram-agentis this is a syntax issue.

@mpretty-cyro You can play around with MSON syntax using our MSON playground https://bukalapak.github.io/mson-playground/
