### ISSUE TITLE
Request with no name doesn't get rendered

### ISSUE THREAD

**Issue by mpretty-cyro** [bukalapak/snowboard#104]
Hey @subosito, there seems to be an issue when defining request data without providing a name. When I use:
```
## Random Post Action [POST]

+ Request (application/json)
    + Attributes
        + value: example (string, required)

+ Response 200
```

Then the request doesn't render, but if I add anything in for the name (like the `-` below) then it renders correctly:
```
## Random Post Action [POST]

+ Request - (application/json)
    + Attributes
        + value: example (string, required)

+ Response 200
```

**Comment by kingsleyh** [comment]
aha I was having this same issue - thanks for the workaround!

**Comment by kingsleyh** [comment]
The same is true of the Attributes as well

**Comment by dimasdanz** [comment]
Having the same issue. +1

**Comment by subosito** [comment]
@mpretty-cyro @kingsleyh Snowboard v3.7.0 handles this correctly. I am going to close this issue. Please reopen if the problem persists.
