### ISSUE TITLE
Palyground doesn't work and breaks everything

### ISSUE THREAD

**Issue by hoghweed** [bukalapak/snowboard#109]
Hi, 
first of all thanks, many thanks for that good job you made.

after that, unfortunately, I'm not able to run the playground, once enabled, if I click on any link, everything stops working, no api open, no playground, also the links for collapsing the sidebar they reuse to work properly. This happens just if I enable the Playground.

Can you help me understand what is going bad?

I'm running an Ubuntu dev machine, with node 12.x, trying to read and use the playground using Firefox.

Node v12.4.0
Npm 6.13.6
Snowboard v3.6.0
Kernel 5.3.0-26-generic

Thanks anyway
Cheers

**Comment by kingsleyh** [comment]
Hi - I have the same problem - I believe this is the same issues as https://github.com/bukalapak/snowboard/issues/108

**Comment by kingsleyh** [comment]
The workaround proposed in #108 works for me

**Comment by subosito** [comment]
@hoghweed @kingsleyh  This issue is fixed by https://github.com/bukalapak/snowboard/commit/37752c5e69a6ac065144639a080ddde643080790. I've rewrite route handling to use a router; you can try v3.7.0 to see it in action.

Feel free to reopen this issue.
