### ISSUE TITLE
Cannot read property 'used' of undefined at `populate`

### ISSUE THREAD

**Issue by slax0rr** [bukalapak/snowboard#111]
Hello,

when trying to dispatch a request to the server using playground, the error occurs at:
![snowboard-bug](https://user-images.githubusercontent.com/3025605/75137608-5794ea80-56e8-11ea-818d-fab133055445.png)

Snowboard version: v3.7.1

apib:
```
FORMAT: 1A

# api

# Group Auth

## Auth Challenge [/auth/challenge/?app-id={client_id}]

### /auth/challenge/ [GET]

+ Parameters
    + client_id (string)

        OAuth2 Application/Client ID

+ Response 200 (application/json)

        {
            "challenge": "random string"
        }
```

**Comment by subosito** [comment]
Thanks for the report @slax0rr.

This has been fixed in https://github.com/bukalapak/snowboard/commit/6ce850266fab048c078f1eeb61ab5ddb00ca2549 and released as part of `v3.7.3`.

Feel free to reopen if the issue persist.
