### ISSUE TITLE
[HELP] Add option to ignore warnings for duplicate routes.

### ISSUE THREAD

**Issue by harshmandan** [bukalapak/snowboard#113]
Aglio builds my doc fine but does give some warning compiling the HTML. Those errors are:

>  action with method 'POST' already defined for resource '/auth/login' (warning code 2)

> the resource '/auth/signup' is already defined (warning code 2)

My api is structured in such a way that an endpoint has multiple ways of being called. So is there any flag or option to build besides these warnings.

**Comment by subosito** [comment]
@harshmandan I think you can post your issue to the Aglio repo. For snowboard one, you can post here.
