### ISSUE TITLE
Cannot generate HTML

### ISSUE THREAD

**Issue by balazs-kis** [bukalapak/snowboard#116]
HTML generation fails with 'TypeError':
`$ snowboard html fc-api.apib`
`✔  Input parsed: fc-api.apib in 38 ms.`
`TypeError: Object.fromEntries is not a function`
`    at buildSeed (/usr/lib/node_modules/snowboard/node_modules/snowboard-packer/lib/builder.js:54:24)`

**Comment by fahrulazmi** [comment]
You probably has outdated version of Node.

**Comment by balazs-kis** [comment]
You are right, `apt` installs an outdated version. Wonder why.
