### ISSUE TITLE
Ignores parameter type

### ISSUE THREAD

**Issue by aburakovskiy** [bukalapak/snowboard#12]
In _api.apib_ file have parameter within integer type:
```
+ Parameters
    + id: (integer, required) - ID of the news record in DB.
```
Execute command `snowboard html -i api.apib -o api.html`
And in the result _api.html_ file it shows type for this parameter is string

```
Snowboard version: v0.5.0
Drafter version: v3.1.2
```

**Comment by subosito** [comment]
I think it has been fixed by https://github.com/bukalapak/snowboard/pull/26. Feel free to reopen.
