### ISSUE TITLE
Error with snowboard-packer

### ISSUE THREAD

**Issue by VulkanX** [bukalapak/snowboard#123]
Getting an error with snowboard-packer/lib/builder.js:54.24

\Programming\DD\API Blueprints>snowboard html DD-IM.apib
√  Input parsed: DD-IM.apib in 57 ms.
TypeError: Object.fromEntries is not a function
    at buildSeed (C:/Users/USER/AppData/Roaming/npm/node_modules/snowboard/node_modules/snowboard-packer/lib/builder.js:54:24)

I've tried this with my apib files and with some example ones and i get the same error, been troubleshooting many issues trying to get it running on windows, I have yet to find any info on this error.

**Comment by subosito** [comment]
@VulkanX for Windows, you can use WSL. Please refer to this https://github.com/bukalapak/snowboard/issues/63#issuecomment-535532528 for more details.
