### ISSUE TITLE
`html` fails due to EISDIR

### ISSUE THREAD

**Issue by daredevil82** [bukalapak/snowboard#125]
I'm building api docs with these three commands run in sequence.  We're pining to 3.7.5 due to issues in `latest`.

    hercule docs/blueprint/internal.apib -o docs/falcon.apib
	docker run -v $(PWD)/docs:/docs --rm quay.io/bukalapak/snowboard:v3.7.5 lint /docs/falcon.apib
	docker run -v $(PWD)/docs:/docs --rm quay.io/bukalapak/snowboard:v3.7.5 html /docs/falcon.apib -o /docs/falcon.html

This presents the output 

    - Processing input: /docs/falcon.apib
    ✖ Rendering HTML documentation
    ERROR: Error: EISDIR: illegal operation on a directory, open '/docs/falcon.html'

Of three members of my team, only I have had this problem, and we're all running on the same configuration

**Comment by subosito** [comment]
@daredevil82 as error `EISDIR` looks like your `/docs/falcon.html` is a directory instead of an HTML file. You can check using:

```
$ file docs/falcon.html
docs/falcon.html: directory
```

It should be:

```
$ file docs/falcon.html
falcon.html: HTML document, UTF-8 Unicode text, with very long lines, with CRLF, LF line terminators
```

You can remove the `falcon.html` first then re-run the docker command.
