### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by bestwebua** [bukalapak/snowboard#126]
Hi! First of all, I wanted to say thank you for this brilliant tool. Yesterday after snowboard update to last version I have faced with error:
```bash
➜ snowboard html -o 'public/api/docs/v1/index.html' 'public/api/docs/v1/apispec.apib'
✔  Input parsed: public/api/docs/v1/apispec.apib in 817 ms.
TypeError: Object.fromEntries is not a function
    at buildSeed (/usr/lib/node_modules/snowboard/node_modules/snowboard-packer/lib/builder.js:56:24)

➜ snowboard -v
snowboard/4.1.7 linux-x64 node-v11.15.0
```
How I can debug this error? Maybe something wrong with my current blueprint markdown. 3.x versions return bad markdown lines if they were.

P.S. With 3.7.3 version everything is ok.

**Comment by subosito** [comment]
@bestwebua Thanks for reporting this. It looks like Babel does not transform `Object.fromEntries`. I've pushed the fix for this in https://github.com/bukalapak/snowboard/commit/cdbf00e5f5911c4a49f6c2254a2dd1c7a87b0ace. Please retry using Snowboard `v4.1.11` and let me know.

**Comment by bestwebua** [comment]
@subosito 
```bash
➜ snowboard html -o 'public/api/docs/v1/index.html' 'public/api/docs/v1/apispec.apib'
✔  Input parsed: public/api/docs/v1/apispec.apib in 818 ms.
Error: ENOTDIR: not a directory, mkdir 'absolute_path_to_project_folder/public/api/docs/v1/index.html/__json__'
```

**Comment by subosito** [comment]
@bestwebua snowboard v4 no longer supports output as a single HTML file; it is using directory as the output. You can try to update your command to:

```
➜ snowboard html -o 'public/api/docs/v1' 'public/api/docs/v1/apispec.apib'
```

**Comment by bestwebua** [comment]
@subosito Thx, there no errors now, but I got blank html as result, instead html with content (as in 3.7.3). Any ideas how could debug this?
