### ISSUE TITLE
Use a lighter Docker image

### ISSUE THREAD

**Issue by hugofcampos** [bukalapak/snowboard#127]
The image is unnecessary super-heavy. Maybe we should use a slim or alpine version.

**Comment by subosito** [comment]
Hi @hugofcampos, sorry for the late info; since Snowboard v4.1.18, as per commit https://github.com/bukalapak/snowboard/commit/fdb3f7534af6782776eacbd357c08f877a10154b, we were migrated to use the lighter image. It's now about 52MB, compared with previously 450MB. Hope you like it 😃
