### ISSUE TITLE
Default body content

### ISSUE THREAD

**Issue by martin-hoger** [bukalapak/snowboard#146]
First of all thank you very mach for a great piece of software!

Is there a way to set a default body value for POST, PUT or PATCH requests? I tried many things but didn't find a way to do that. I am missing the body part in the curl example (by default, the body section would be empty, which results in incomplete curl query):

![Selection_009](https://user-images.githubusercontent.com/2011520/88034788-79808500-cb41-11ea-9a79-255c96fe8fdf.png)

This is what i tried to achieve:

![Selection_008](https://user-images.githubusercontent.com/2011520/88033796-12ae9c00-cb40-11ea-893f-04c043f1206d.png)

Is there a way to do that?

Apiary pre-populates the body section from the request, would be be an option?

![Selection_010](https://user-images.githubusercontent.com/2011520/88035496-89e52f80-cb42-11ea-9695-4dd31c6ab64f.png)

Thank you!

---------------------

```
## User Account Collection [/accounts]

Admins can fetch and manage all user accounts and their profile properties.

### Create [POST]

+ Request (application/vnd.api+json)

    + Headers

            Accept: application/vnd.api+json
            Authorization: Bearer sessionid123

    + Body

            {
                "data": {
                    "type": "account",
                    "attributes": {
                        "username": "jane-doe",
                        "password": "secret"
                    }
                }
            }

+ Response 201 (application/vnd.api+json)

    + Headers

            Location: https://example.com/accounts/abc4567

    + Body

            {
                "links": {
                    "self": "https://example.com/accounts/abc4567"
                },
                "data": {
                    "id": "abc4567",
                    "type": "account",
                    "attributes": {
                        "username": "jane-doe"
                    },
                    "relationships": {
                        "profile": {
                            "links": {
                                "related": "https://example.com/accounts/abc4567/profile"
                            },
                            "data": {
                                "id": "abc4567-profile",
                                "type": "profile",
                            }
                        }
                    }
                }
            }

+ Response 401 (application/vnd.api+json)

        {
            errors: [{
                "status": "401",
                "title": "Unauthorized",
                "detail": "Authorization header missing"
            }]
        }

```

**Comment by subosito** [comment]
Hi @martin-hoger, this has been fixed in https://github.com/bukalapak/snowboard/pull/159. You can update snowboard to v4.1.21 to see it in action (a long with a fancy ACE editor).
