### ISSUE TITLE
PATCH: curl command is not displayed correctly

### ISSUE THREAD

**Issue by martin-hoger** [bukalapak/snowboard#147]
When using the PATCH method, the curl command is not displayed correctly (it shows "GET" and doesn't include the body part):

![Selection_011](https://user-images.githubusercontent.com/2011520/88188802-9ea3ef00-cc38-11ea-9d67-bb9d79ea84bf.png)

The issue is only concerning the PATCH method, when I change the request to POST or PUT, it works as expected.

**Comment by subosito** [comment]
Closing this; this issue has been fixed in snowboard v4.1.14

**Comment by martin-hoger** [comment]
Cool. Thank you!
