### ISSUE TITLE
How can i add several responses

### ISSUE THREAD

**Issue by sajadabasi** [bukalapak/snowboard#19]
How can I add several responses for a request?
like:
```

### Create a Coupon [POST]
Creates a new Coupon.

+ Attributes (object)
    + percent_off: 25 (number)
    + redeem_by (number)

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Coupon)

+ Response 404 (application/json)
    + Attributes 
        + testName: test 


```

**Comment by fricklerhandwerk** [comment]
You can't because of API blueprint. See [here](https://stackoverflow.com/a/22025252). Add multiple requests if you need more than one example request-response pair.

**Comment by shadowhand** [comment]
@fricklerhandwerk this is no longer true, as per the Blueprint spec:

> NOTE: A blueprint document may contain multiple sections for the same resource (or resource set), as long as their HTTP methods differ. However it is considered good practice to group multiple HTTP methods under one resource (resource set).

https://apiblueprint.org/documentation/specification.html#action-section

> Multiple Request and Response nested sections within one transaction example should have different identifiers.

So long as the response code differs, it is possible to have multiple responses for a single request.
