### ISSUE TITLE
Can you trigger multiple responses with mock server?

### ISSUE THREAD

**Issue by markacianfrani** [bukalapak/snowboard#27]
I have a very basic apib file that can return multiple responses (200, 400, 401) for a single request. When I run the mock server, it shows all the available responses as available routes, it just only ever returns the first one. 

It looks like the apiary mock server allows you to specify which response by using a [prefer header](https://help.apiary.io/tools/mock-server/#multiple-responses). Is something similar supported here?

**Comment by subosito** [comment]
@markacianfrani You can use `X-Status-Code: <status-code>` header for that purpose. I will add `Prefer` header soon, so we can use same syntax as apiary mock server.

**Comment by markacianfrani** [comment]
Perfect! Thank you. (I wish I knew Go so I could contribute)
