### ISSUE TITLE
expose the ast/api elements parse result

### ISSUE THREAD

**Issue by CrowdHailer** [bukalapak/snowboard#30]
Is there a way to use snowboard to return the [api elements](https://github.com/apiaryio/api-elements) intermediate parse result using snowboard from docker?

Something like

```
docker run -it --rm bukalapak/snowboard elements my_app.apib
```

**Comment by subosito** [comment]
@CrowdHailer Just pushed some changes, now you can do:

```
# output using stdout
$ docker run -it --rm bukalapak/snowboard json my_app.apib

# or, output as file
docker run -it --rm bukalapak/snowboard json -o elements.json my_app.apib
```
