### ISSUE TITLE
Feature Request: Watch mode/Auto reload

### ISSUE THREAD

**Issue by spawnia** [bukalapak/snowboard#33]
Snowboard is working great, however i am missing this functionality.

I would like to run the html generation in watch mode. This could either be in a fixed interval using `watch` or using file system events via `inotifywatch`.  When running the tool natively on linux, those are usually available. However, i am running it in a docker container - which does not have them.

If you could add such functionality via some command line flags or add the mentioned cli tools to the docker image, that would be great.

**Comment by subosito** [comment]
Hi @spawnia , just implemented in 7167fb5, please re-open the issue if the implementation is not working on your side.

**Comment by spawnia** [comment]
I just experimented with it, and stumbled upon a few problems:

1. The container uses `snowboard` as an entrypoint. This itself is not the issue, and makes for comfortable usage of snowboard itself. However, when i want to run `inotifywatch`, i first need to overwrite the entrypoint.

2. In my particular case, i am mounting from a Windows machine. Because of this, `inotify` does not pick up on file changes. I did solve this issue by simply wrapping the `snowboard` call in watch:
````bash
docker run -it -v $PWD:/doc --entrypoint /bin/sh bukalapak/snowboard
apt update && apt install procps
watch snowboard html -o api.html api-description.apib
````

For ease of use, adding a flag to the command line would be the most comfortable solution.
````
--watch  Watch for file changes
````

For performance, using `inotify` events  is best, although it has the problem of not working on MacOS/Windows filesystems. Because of this, i suggest either polling for changes on the file or simply rerunning the command every X seconds. Since we are only dealing with a few files, the performance hit should not matter all that much.

Unfortunately, i do not know GO, but if you do not feel like implementing this yourself - i might just take this as an opportunity to learn it and try and contribute. Maybe we can work together on this.

**Comment by subosito** [comment]
Hi @spawnia sorry, just got a chance to check this issue on a Windows machine. You're right, it doesn't work on those, since `inotify` not yet support Windows. To fix this, as you suggested, I've implemented polling for changes mechanism in addition of inotify-based watcher.

With these changes you can now run on your windows docker:

```
$ docker run -v ${PWD}:/doc bukalapak/snowboard html --watch --watch-interval 200ms -s api-description.apib
```
Please let me know if this solution works (or not) on your side :smiley:

**Comment by spawnia** [comment]
Thanks for the effort!

Unfortunately, adding `--watch --watch-interval 200ms` causes snowboard to go into listening mode, even if i specify to output the html to a file.

My command is:
`docker run -v ${PWD}:/doc bukalapak/snowboard --watch --watch-interval 200ms html -o public/index.html api-description.apib`

Snowboard does pick up on the change to the blueprint file, but instead of rerendering the html and writing it to `index.html`, it spews out the whole html to the console.
