### ISSUE TITLE
Generated HTML tries to fetch non-existent CSS and JS files

### ISSUE THREAD

**Issue by jwolfeld** [bukalapak/snowboard#35]
I used the docker image to execute Snowboard.

The generated HTML includes links to files that cannot be found.  Here is the browser's console output:

`
cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
cdnjs.cloudflare.com/ajax/libs/prism/1.5.1/themes/prism-okaidia.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
jquery.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
accordion.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
tab.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
transition.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
popup.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
prism.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
prism-json.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
output.html:9771 Uncaught ReferenceError: $ is not defined
    at output.html:9771
`

**Comment by subosito** [comment]
Please see this answer https://github.com/bukalapak/snowboard/issues/15#issuecomment-285396822.

**Comment by jwolfeld** [comment]
Perfect explanation - thanks.
