### ISSUE TITLE
Rendered html is virtually empty if the blueprint file contains {{ }}

### ISSUE THREAD

**Issue by michaelgwelch** [bukalapak/snowboard#36]
A recent edit to our API document resulted in our rendered HTML being virtually empty.

We traced down the issue to the use of double braces in the api blueprint document.

For example part of the document looked like this

```
    + username (string, required) - {{Username}}
    + password (string, required) - {{Password}}
```

The Aglio parser (which we also use) renders this without issue. But Snowboard has an issue.

**Work Around:** We discovered a work around. Using the HTML decimal encodings of these characters everything was fine

```
    + username (string, required) - &#123;&#123;Username&#125;&#125;
    + password (string, required) - &#123;&#123;Password&#125;&#125;
```

**Comment by michaelgwelch** [comment]
Note: We tried other work arounds like enclosing the offending block of text in backticks.

Creating a fenced code block with ` ``` ` and finally using html `<pre>` tags. None of these attempts resolved the issue.

**Comment by michaelgwelch** [comment]
We found that our workaround cannot be used in all cases. For example, in a Header section which must be a code block. The HTML Decimal encodings are rendered as-is `&#123;` rather than as braces `{`

So we have just decided to use a different notation to indicate a placeholder.

**Comment by mavimo** [comment]
same issue here
