### ISSUE TITLE
URI parameter members

### ISSUE THREAD

**Issue by nbob** [bukalapak/snowboard#4]
Hi
How can I access `Members` defined in my URI parameter in template?

```
+ Parameters
    + type (enum[string]) - Enum parameter
        + Members
            + `option_1`
            + `option_2`
            + `option_3`
```

https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#description-13

**Comment by fricklerhandwerk** [comment]
As far as I can see there is no API for that. @subosito I kindly request this!
