### ISSUE TITLE
Array types are not properly displayed

### ISSUE THREAD

**Issue by kennydude** [bukalapak/snowboard#40]
When using Data Structures which may use an array for sub-objects, the generated schema does not fully describe the sub-objects but the example is correct.

Ideally I would like to be able to have a way of showing what each property inside the array is supposed to mean. A feature that Apiary has, but sadly not Snowboard

**Comment by DavidBM** [comment]
you need to add fixed-type as the last argument of the type. Like this:

```
- `plans` (array[location_plan], optional, fixed-type)
```
