### ISSUE TITLE
Docker-Container automated build fails

### ISSUE THREAD

**Issue by BreiteSeite** [bukalapak/snowboard#49]
We are unable to pull a new version of the container due to build problems on Docker Hub.

See: https://hub.docker.com/r/bukalapak/snowboard/builds/bxcvhfto46j2edka8aokgfk/

**Comment by subosito** [comment]
This is related to https://github.com/bukalapak/snowboard/issues/47#issuecomment-398593964.

@BreiteSeite Feel free to use the one from [Quay.io](https://quay.io/repository/bukalapak/snowboard?tab=tags).
