### ISSUE TITLE
Reload is not triggered on OSX 10.11.6

### ISSUE THREAD

**Issue by honzatrtik** [bukalapak/snowboard#5]
when I run snowboars server via
`snowboard  -i apiary.apib -o doc/index.html -b 0.0.0.0:8088 -s`
the file is generated only on start, the watcher is probably somehow broken...

**Comment by andrewvmail** [comment]
im seeing this too, installed using homebrew 0.5.0

**Comment by kbredemeier** [comment]
Looks like the the template doesn't include livereload but it works fine using the [livereload browser extension](http://livereload.com/extensions/).
