### ISSUE TITLE
Issue when generating HTML docs on macOS 10.14 

### ISSUE THREAD

**Issue by igorbolic** [bukalapak/snowboard#50]
I have the following version of Snowboard.

**Snowboard version: v1.4.0
Drafter version: v3.2.7**

Generating API HTML does not seem to work on **OSX 10.14**. When running:

`snowboard html -o API.html API.md`

The HTML is generated with invalid links to stylesheets & JS files e.g. instead of:

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css">`

the following link is generated:

`<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/semantic.min.css">`

Everything works fine when generating HTML via docker:

`docker run -it --rm -v $PWD:/doc quay.io/bukalapak/snowboard html -o API.html API.md`

**Comment by subosito** [comment]
It has been fixed in PR https://github.com/bukalapak/snowboard/pull/44 and release `v1.5.0` onwards.
