### ISSUE TITLE
Auto-regeneration using --watch does not work with Included apib files

### ISSUE THREAD

**Issue by ksingh7** [bukalapak/snowboard#55]
@subosito  First of all snowboard is awesome !!! Thanks for maintaining this.

I have a minor issue, auto-regeneration does not seem to be working using Docker. I am using the following command.

```
docker run -it --rm -v $PWD:/doc -p 8088:8088 quay.io/bukalapak/snowboard --watch --watch-interval 100ms html -o index.html -b 0.0.0.0:8088 -s index.apib
```

Any advice to this is welcome.

**Comment by ksingh7** [comment]
``--watch --watch-interval 100ms`` works in general. But it 
- Does not work if you have ``<!-- include(basic.apib) -->`` .i.e. any chnages to included apib files are not getting re-generated
- Only works if you do any change the master *.apib file

**Comment by subosito** [comment]
Hi @ksingh7, could you try `v2.0.7`? we have added support for watching nested partials. Please let me know if it's working on your side.

**Comment by subosito** [comment]
Going to close this issue for now, please reopen if needed.
