### ISSUE TITLE
Partials fails for included files

### ISSUE THREAD

**Issue by betterphp** [bukalapak/snowboard#60]
When using the `<!-- include(whatever.apib) -->` syntax in a file that's being included by the file being parsed an error message is shown. We include a list of files for each endpoint then those include some .json schemas which is where the problem occurs.

Badly worded so here's an example.

test.apib
```
# Test API

<!-- include(other-file.apib) -->
```

other-file.apib
```
<!-- include(example-schema.json) -->
```

example-schema.json
```
{
    "the": "json"
}
```

Running `./snowboard lint test.apib` outputs
```
The partial example-schema.json could not be found
```
However running `./snowboard lint other-file.apib` works.

The same thing happens when using any file format, it's not something specific to json files.

**Comment by betterphp** [comment]
We're working around this for now using a script to compile the apib files into one before rendering

```js
#!/usr/bin/env node
const fs = require("fs");

/**
 * Gets the contents of a file and resolves includes
 *
 * @param {string} filePath The path to read
 * @param {string} prepend String to prepend to all lines of the file
 *
 * @return {string} The compiled file
 */
const getCompiledText = (filePath, prepend = "") => {
    let contents = fs.readFileSync(filePath, "utf8");

    if (prepend) {
        contents = contents.replace(/^/gm, prepend);
    }

    return contents.replace(
        /([ \t]*)<!-- include\((.+)\) -->/gi,
        (match, prependString, includedFilePath) => {
            return getCompiledText(includedFilePath, prependString);
        }
    );
}

const compiled = getCompiledText("index.apib")

fs.writeFileSync("compiled.apib", compiled);
```

**Comment by emilsedgh** [comment]
This prevents us from using snowboard as well.

In our case it happens with nested partials.

The first include works. It's the second include that breaks.

**Comment by subosito** [comment]
It has been fixed in https://github.com/bukalapak/snowboard/commit/28b49e346a98659edbc3db132eadfb8904b2704b  and https://github.com/bukalapak/snowboard/commit/75478505de26cae36a402c5d677ed478bc455170. It's also available on release `v2.0.5`.

@betterphp and @emilsedgh, could you try the release and see if it's working on your side?

**Comment by betterphp** [comment]
@subosito Yep seems to work now. Thanks :smiley:

**Comment by subosito** [comment]
Awesome @betterphp :+1:
