### ISSUE TITLE
docker -t template.html 

### ISSUE THREAD

**Issue by jeffotoni** [bukalapak/snowboard#61]
It does not generate TEMPLATE as a parameter using docker.

$ docker run -it -rm -v $ PWD: / doc quay.io/bukalapak/snowboard html -o output.html -t slate-triple.html API.apib

It generates the output.html with the template and not with the API.apib

**Comment by subosito** [comment]
Looks like similar #59. Could you retry with version `v2.0.4` or `latest` tag, and see the difference?

**Comment by subosito** [comment]
Going to close this issue for now, please reopen if needed.
