### ISSUE TITLE
JSON preformatted code block

### ISSUE THREAD

**Issue by kamk** [bukalapak/snowboard#62]
Style conflict resolution between prism and bulma doesn't apply in markdown's language-specific code block. The blueprint example file is in the attachment.

[simplest_with_json_code_block.txt](https://github.com/bukalapak/snowboard/files/3396320/simplest_with_json_code_block.txt)

**Comment by subosito** [comment]
@kamk please retry using `v3.0.0-rc.3` which includes a fix for this issue and markdown rerendering issue.

**Comment by kamk** [comment]
Great, it's fixed!
