### ISSUE TITLE
Playground requests ignore parameters

### ISSUE THREAD

**Issue by danielpoonwj** [bukalapak/snowboard#64]
Hi,

Thank you for your work! I've been evaluating `snowboard` and it's a great tool. One issue I faced is with the playground requests not including the parameters.

![Screen Shot 2019-08-13 at 12 44 39 PM](https://user-images.githubusercontent.com/17039704/62916374-c359da80-bdca-11e9-8332-7e6b3a003594.png)

From what I understand from the briefly looking at the code, is that the param `{msg: "test"}` should be interpolated with the uritemplate provided `{?msg}` to make the GET request `http://localhost:8080/heartbeat?msg=test`.

This is the apib used to generate the html, do let me know if it's user error on my part.

```apib
FORMAT: 1A

# Demo

## Heartbeat

### Get Heartbeat [GET /heartbeat{?msg}]

+ Parameters
    + msg: `ok` (string, optional)
        + Default: ok

+ Response 200 (application/json)

    + Body

            {
                "msg": "ok"
            }

```

**Comment by subosito** [comment]
Hi, @danielpoonwj thanks for opening this issue. It happens because of missing axios options, and https://github.com/bukalapak/snowboard/commit/44f2330fe473fb87f53d9ed28c66e851ff1d1070 fixes this issue. You can retry using `v3.1.8` I've just published.

**Comment by danielpoonwj** [comment]
thank you so much @subosito for the amazing turnaround time, works great now!
