### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by jramcast** [bukalapak/snowboard#65]
While trying to use a custom template with the command

`docker run -it --rm -v $PWD/docs:/doc quay.io/bukalapak/snowboard html --watch  -o generated.html -c config.yaml -t template/mytemplate.html API.apib",`

I am receiving this message:

```
'/doc/template/mytemplate.svelte' is imported by ../tmp/tmp-14IfCZ5HN75UO, but could not be resolved – treating it as an external dependency
No name was provided for external module '/doc/template/mytemplate.svelte' in output.globals – guessing 'App'
```

Do I need to create a full Svelte app? What is the process for this in case we only want to customize some css?

**Comment by jramcast** [comment]
The error seems to occur only when running the snowboard docker container, so perhaps something is missing in the image.

**Comment by subosito** [comment]
Thanks @jramcast, I will investigate the docker container.

Yes, currently, that's the way how template customization. It's not pleasant for small changes, but if you have a completely different template, it's a freedom :).

But, yeah, I am going to make some adjustments to make it easier for small changes. Perhaps, allowing custom CSS? Or any idea?

**Comment by jramcast** [comment]
Hi @subosito, I guess something like CSS custom properties or even Less or Sass would do it for small style changes.

On the other hand, more hardcore changes will require the modification of templates or even app logic, so having full control over the svelte app seems like a good choice.

**Comment by fedeisas** [comment]
@jramcast any tips to compile the template locally? Thanks a lot.

**Comment by jramcast** [comment]
@fedeisas The only way I found to fully customize the output is creating my own template, which means creating your own svelte app, and if you want/wish, reusing some parts of the default template. Then you can compile it with something like this:

```sh
snowboard html -o OUTPUT_FILE.html -c docs/config.yaml -t YOUR_TEMPLATE.html API_BLUEPRINT_FILE.apib
```
You'll probably want to take a look at the svelte docs, as you basically need to create a new app with this library.
