### ISSUE TITLE
Bug in 3.4.1

### ISSUE THREAD

**Issue by nilskp** [bukalapak/snowboard#79]
Sorry I can't provider better info, but I tried 3.4.1 and got this error:

`dataStructure.content.content.map is not a function`

Switched back to 3.4.0, which works.

Info: I'm running this from a Gradle script in the WSL bash, if that's any help.

**Comment by nilskp** [comment]
@subosito 
Any idea what is causing this from 3.4.1 onwards? It's still in 3.5.2 also.

I'm stuck on 3.4.0.

**Comment by subosito** [comment]
@nilskp could you post a snippet of the affected apib? I couldn't reproduce yet.

**Comment by nilskp** [comment]
This does not fix the problem.

However, I've figured out what's causing this (I think): An `enum` definition with a single value. E.g.:

```
FORMAT: 1A

# Foo

## Data Structures

### JustOne (enum)
- Hello

```

**Comment by mpretty-cyro** [comment]
@subosito Also running into the same problem and can confirm it's caused in my blueprint by an enum with a single case.
