### ISSUE TITLE
Support HTML rendering from Grunt

### ISSUE THREAD

**Issue by hankipanky** [bukalapak/snowboard#83]
I'd like to create a grunt task that loads, lints and renders the result to HTML. My problem is currently that the module only exports `load` and `lint`, not `htmlBundle`.

Is it possible to export this functionality as well? Or is it possible to render the output from grunt, and I'm just not seeing it? Thx...

**Comment by subosito** [comment]
You can actually do:

```js

import { htmlBundle } = require("snowboard/lib/command")

// in async function
await htmlBundle("doc.apib");


```
