### ISSUE TITLE
Cannot read property 'resourceGroups' of undefined

### ISSUE THREAD

**Issue by andzejsw** [bukalapak/snowboard#89]
Command `snowboard html -o output.html API.apib` for me resulted with error `Cannot read property 'resourceGroups' of undefined`.
I am not using docker. Just called required code using `npm run <script>` command!

**Comment by MelzerC** [comment]
Did you double check your blueprint file? I always encounter this error when I have an error in the `apib` file. You may also try one of the example blueprints from the official website (https://apiblueprint.org/documentation/examples). The "Real World API" Example should work.

But I agree that the error message isn't very helpful

**Comment by andzejsw** [comment]
> Did you double check your blueprint file? I always encounter this error when I have an error in the `apib` file. You may also try one of the example blueprints from the official website (https://apiblueprint.org/documentation/examples). The "Real World API" Example should work.
> 
> But I agree that the error message isn't very helpful

Yes. I even used your mentioned example file. Maybe i created apib file in wrong way, else i have now clue why this happened.

**Comment by andzejsw** [comment]
> Did you double check your blueprint file? I always encounter this error when I have an error in the `apib` file. You may also try one of the example blueprints from the official website (https://apiblueprint.org/documentation/examples). The "Real World API" Example should work.
> 
> But I agree that the error message isn't very helpful

At the same time everything works ok if i use same `.apib` file for `aglio` package. But i am migrating away from it because of vulnerabilities.

**Comment by MelzerC** [comment]
Could you explain what exactly you mean by saying?
> Just called required code using `npm run <script>` command!

**Comment by andzejsw** [comment]
> Could you explain what exactly you mean by saying?
> 
> > Just called required code using `npm run <script>` command!

Script was defined in package json file and i just runed ir.
Looks like this was file type related issue. I created again same file using editor from this url: https://elfrog.github.io/apib-editor/ and script now was working.

**Comment by surajkj** [comment]
snowboard html -o index.html test.apib
× Processing input: test.apib
ERROR: TypeError: Cannot read property 'resourceGroups' of undefined

Facing same issue. Is it due to python dependency. It requires python version < 3 & I have python 3.7
.
Got

**Comment by MelzerC** [comment]
> snowboard html -o index.html test.apib
> × Processing input: test.apib
> ERROR: TypeError: Cannot read property 'resourceGroups' of undefined
> 
> Facing same issue. Is it due to python dependency. It requires python version < 3 & I have python 3.7
> .

While working on my project I noticed you definitely **have to use spaces** for indentation. As soon as I put tabs in the file, the parsing breaks. I guess that's the issue @andzejsw had before. So I suggest you check your file as well? Maybe try the editor linked above.

Nevertheless: For your further investigation, I am using python 2.7.16
