### ISSUE TITLE
Implement Snowboard with React or Angular

### ISSUE THREAD

**Issue by gogears** [bukalapak/snowboard#90]
1) How to implement snowboard with existing ReactJS or AngularJS application
2) Is it possible to implement routing or private routing after integrating snowboard
3) When iam importing it as a component, it throws an error as attachment 
<img width="1044" alt="Screenshot 2019-11-14 at 1 51 41 PM" src="https://user-images.githubusercontent.com/6576486/68839066-ee174000-06e5-11ea-8efb-8426d3217eaa.png">

**Code Sample:**
<img width="375" alt="Screenshot 2019-11-14 at 1 53 23 PM" src="https://user-images.githubusercontent.com/6576486/68839182-29197380-06e6-11ea-8f7e-c981818160a6.png">

**Comment by subosito** [comment]
Snowboard is built using [svelte](https://svelte.dev), so it's not possible to import it as a component.

The exported functions are for parsing, linting, and producing html.
