### ISSUE TITLE
Error: the use of carriage return(s) '\r' in source data isn't currently supported

### ISSUE THREAD

**Issue by andzejsw** [bukalapak/snowboard#93]
`Error: the use of carriage return(s) '\r' in source data isn't currently supported, please contact makers (error: line 1, column 11;line 1, column 11)`
This error for me appeared after fix for error [https://github.com/bukalapak/snowboard/issues/89](https://github.com/bukalapak/snowboard/issues/89)
My line 1 is `FORMAT: 1A`. Also error appeared, only when i reverted changes using VS Code. Only way to fix it now for me is to remake .apib file from scratch, as i mentioned it in issue #89

**Comment by andzejsw** [comment]
Using `Beyond Compare` i am seeing that binaries between previous .apib file are different, while file contents are the same. Both are UTF-8; Working one is made on UNIX, not working is made on PC. Also working one is lighter.

**Comment by subosito** [comment]
Thanks for reporting, this is beyond snowboard, since it's drafter's (snowboard underlying parser) issue, as you can see on https://github.com/apiaryio/drafter/issues/628.

Please ensure you replace all tabs using spaces, and carriage return using line feed.

**Comment by andzejsw** [comment]
Why is this issue closed, if issue in drafter is still not resolved?

**Comment by subosito** [comment]
Hi @andzejsw, as I said earlier, this issue is beyond snowboard scope. The fix for this issue must be implemented on the drafter side.
