### ISSUE TITLE
Remove schema?

### ISSUE THREAD

**Issue by trende-jp** [bukalapak/snowboard#95]
Is removing the schema easily done?

https://github.com/infinum/dox does not seem to produce data for the schema area.

**Comment by MSchmidt** [comment]
True, the schema tab really doesn't need to be there, when there's no schema.

**Comment by subosito** [comment]
This has been implemented on https://github.com/bukalapak/snowboard/commit/fba0eb91defff88cb96323bf6befc7759b933242. Please use Snowboard v3.7.1 for this.
