### ISSUE TITLE
httpServer doesn't stop on ^C 

### ISSUE THREAD

**Issue by ulidtko** [bukalapak/snowboard#97]
This tool is clearly intended for command-line usage, but doesn't react to SIGINT properly.

So to stop `snowboard -w http doc/myapi.md`, the user has to do the <kbd>Ctrl</kbd><kbd>Z</kbd>, `kill %1`, `fg` dance; or perhaps something else involving `kill` in another terminal.

Instead, the http server should stop gracefully in response to the INT signal.

**Comment by subosito** [comment]
Closing this as ^C is working as expected.
